### ISSUE TITLE
Build time counter resets to zero after hour of build.

### ISSUE THREAD

**Issue by igorushi** [nagits/BuildVision#11]
Hi, 
First of all thanks for nice extension. I know that long builds are not very usual but it will be nice if buildvision could show also hours (or more than 59 minutes).
Thanks.

**Comment by nagits** [comment]
Hi @igorushi,
You can configure BuildVision via "TOOLS -> Options... -> BuildVision".

Then "Build Messages -> Elapsed time": 
* change "Time template" to TotalMinutes:Seconds
* or "Time format" to hh\\:mm\\:ss

**Comment by igorushi** [comment]
Cool, it looks like [total_minutes:seconds] format is great for me.

Thank you.
