### ISSUE TITLE
BV causes taskbar icon to flash

### ISSUE THREAD

**Issue by vaindil** [nagits/BuildVision#16]
When a site builds as a result of clicking the Run button, the VS icon on the taskbar gets a green background and it stays there until the VS window is given focus. Is it possible to fix this? The taskbar icon normally fills up with the progress of the build whether BV is running or not, but it looks like BV doesn't clear it out like VS normally does.

![capture](https://cloud.githubusercontent.com/assets/771134/11040798/098d4746-86dc-11e5-8c11-85f2973b0d59.PNG)

**Comment by nagits** [comment]
Hi @vaindil,

You can configure it via Tools -> Options... -> BuildVision -> General
![image](https://cloud.githubusercontent.com/assets/4932134/11040961/30a11e18-8739-11e5-8d90-b84f1f832d8c.png)

**Comment by vaindil** [comment]
Well, I should've checked there first. Thank you!
