### ISSUE TITLE
Do you plan to continue the UserVoice forum? If please reconsider to add URL again?

### ISSUE THREAD

**Issue by MartinL0815** [nagits/BuildVision#2]
Hi,

Since the update to 1.3 I didn't found the URL to the UserVoice forum again in the UI of BuildVision, nor in its settings.

May you add the URL again? And a direct URL to github?

Best regards,

Martin

**Comment by nagits** [comment]
Hi Martin,

No, I don't. I would like to use GitHub Issues instead of UserVoice forum.
I will think over where to add the URL to the github repo in the UI.

**Comment by MartinL0815** [comment]
Thanks for the information! :+1:
