### ISSUE TITLE
Why not starting/showing elapsed time in the row of the current build project?

### ISSUE THREAD

**Issue by MartinL0815** [nagits/BuildVision#3]
Hi,

I don't know, if I remember it correctly, but I feel like missing the elapsed time in the row of the currently building project!

In the current BuildVision version the elapsed time will show up after a project got built, but why not starting to show the increasing elapsed time in the row of the currently building project with starting the build of this project?

Kind regards,

Martin

**Comment by nagits** [comment]
@MartinL0815 Great idea, I'll try to implement it!

For now and in previous versions [BuildElapsedTime](https://github.com/nagits/BuildVision/blob/0a3f0b8b13011fcfe36a2afb51e71d9ae396ec1e/Source/Tool/Models/ProjectItem.cs#L249-L258) is computed simply as a difference between BuildFinishTime and BuildStartTime. But during the build BuildFinishTime is null, so BuildElapsedTime also null.

**Comment by michael-hawker** [comment]
I think this may have regressed. I installed the latest 3.0.2.2 version and I didn't see the `ElapsedTime` column updating for the row marked `Building`. It stayed at `00:00`:

![image](https://user-images.githubusercontent.com/24302614/129986576-c757692a-bf05-4596-abb1-9320fd4fc1c1.png)
