### ISSUE TITLE
Clicking on errors jump to wrong source file

### ISSUE THREAD

**Issue by PaulSinnema** [nagits/BuildVision#4]
Sometimes when error messages are shown and I click on them Visual Studio jumps to the wrong source file in the project / solution. My guess it has to do something with names not being unique in our projects. We for instance have many 'Default.aspx.cs' files. Can it be that the algorithm that searches for files in the solution / project returns the first hit on just the Filename and not the Fullpath?

**Comment by nagits** [comment]
Hi @PaulSinnema, 
I just reproduced the case, when the project have many 'Default.aspx.cs' files, and found a bug in the [search algorithm](https://github.com/nagits/BuildVision/blob/ad6855b378a63beeeb619ac3fb1b5e61c5045239/Source/Helpers/SolutionProjectsExtensions.cs#L519). It uses relative paths (e.g. Default.aspx.cs or OtherFolder/Default.aspx.cs or Account/Login.aspx.cs) and works well in most cases, but in the case of nested items like 'Default.aspx' ( -> Default.aspx.cs, Default.aspx.designer.cs) it returns the first hit on the Filename.

**Comment by PaulSinnema** [comment]
Hi Aleksey,

 

That was fast. Thanks.

 

Regards

Paul

 

Van: Aleksey Nagovitsyn [mailto:notifications@github.com] 
Verzonden: donderdag 30 april 2015 15:40
Aan: nagits/BuildVision
CC: PaulSinnema
Onderwerp: Re: [BuildVision] Clicking on errors jump to wrong source file (#4)

 

Closed #4 <https://github.com/nagits/BuildVision/issues/4> .
