### ISSUE TITLE
Build duration does not show information for hours

### ISSUE THREAD

**Issue by Bertk** [nagits/BuildVision#6]
I like this extension but I miss some Information in the "build solution" header. Unfortunately I have a very large solution with approx. 300 C++ targets and some C#. The duration exceeds 1 hour.

**Comment by nagits** [comment]
Hi @Bertk,
This header may be configured via Tools -> Options... -> BuildVision -> Build Messages

**Comment by Bertk** [comment]
Thanks for the hint. I missed this configuration item.
